################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Src/user_adc.c \
C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Src/user_at.c \
C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Src/user_i2c.c \
C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Src/user_internal_mem.c \
C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Src/user_obis.c \
C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Src/user_uart.c 

OBJS += \
./Usercode/user_change/Src/user_adc.o \
./Usercode/user_change/Src/user_at.o \
./Usercode/user_change/Src/user_i2c.o \
./Usercode/user_change/Src/user_internal_mem.o \
./Usercode/user_change/Src/user_obis.o \
./Usercode/user_change/Src/user_uart.o 

C_DEPS += \
./Usercode/user_change/Src/user_adc.d \
./Usercode/user_change/Src/user_at.d \
./Usercode/user_change/Src/user_i2c.d \
./Usercode/user_change/Src/user_internal_mem.d \
./Usercode/user_change/Src/user_obis.d \
./Usercode/user_change/Src/user_uart.d 


# Each subdirectory must supply rules for building sources it contributes
Usercode/user_change/Src/user_adc.o: C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Src/user_adc.c Usercode/user_change/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32L072xx -DCMWX1ZZABZ0XX -DDEVICE_TYPE_STATION -c -I../../../SubGHz_Phy/App -I../../../SubGHz_Phy/Target -I../../../Core/Inc -I../../../../../../../../Utilities/misc -I../../../../../../../../Utilities/timer -I../../../../../../../../Utilities/trace/adv_trace -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/BSP/B-L072Z-LRWAN1 -I../../../../../../../../Drivers/BSP/CMWX1ZZABZ_0xx -I../../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../../../../../Middlewares/Third_Party/SubGHz_Phy/sx1276 -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_app/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_device/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_generate/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_util/Inc" -Os -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Usercode/user_change/Src/user_at.o: C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Src/user_at.c Usercode/user_change/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32L072xx -DCMWX1ZZABZ0XX -DDEVICE_TYPE_STATION -c -I../../../SubGHz_Phy/App -I../../../SubGHz_Phy/Target -I../../../Core/Inc -I../../../../../../../../Utilities/misc -I../../../../../../../../Utilities/timer -I../../../../../../../../Utilities/trace/adv_trace -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/BSP/B-L072Z-LRWAN1 -I../../../../../../../../Drivers/BSP/CMWX1ZZABZ_0xx -I../../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../../../../../Middlewares/Third_Party/SubGHz_Phy/sx1276 -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_app/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_device/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_generate/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_util/Inc" -Os -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Usercode/user_change/Src/user_i2c.o: C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Src/user_i2c.c Usercode/user_change/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32L072xx -DCMWX1ZZABZ0XX -DDEVICE_TYPE_STATION -c -I../../../SubGHz_Phy/App -I../../../SubGHz_Phy/Target -I../../../Core/Inc -I../../../../../../../../Utilities/misc -I../../../../../../../../Utilities/timer -I../../../../../../../../Utilities/trace/adv_trace -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/BSP/B-L072Z-LRWAN1 -I../../../../../../../../Drivers/BSP/CMWX1ZZABZ_0xx -I../../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../../../../../Middlewares/Third_Party/SubGHz_Phy/sx1276 -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_app/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_device/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_generate/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_util/Inc" -Os -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Usercode/user_change/Src/user_internal_mem.o: C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Src/user_internal_mem.c Usercode/user_change/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32L072xx -DCMWX1ZZABZ0XX -DDEVICE_TYPE_STATION -c -I../../../SubGHz_Phy/App -I../../../SubGHz_Phy/Target -I../../../Core/Inc -I../../../../../../../../Utilities/misc -I../../../../../../../../Utilities/timer -I../../../../../../../../Utilities/trace/adv_trace -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/BSP/B-L072Z-LRWAN1 -I../../../../../../../../Drivers/BSP/CMWX1ZZABZ_0xx -I../../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../../../../../Middlewares/Third_Party/SubGHz_Phy/sx1276 -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_app/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_device/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_generate/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_util/Inc" -Os -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Usercode/user_change/Src/user_obis.o: C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Src/user_obis.c Usercode/user_change/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32L072xx -DCMWX1ZZABZ0XX -DDEVICE_TYPE_STATION -c -I../../../SubGHz_Phy/App -I../../../SubGHz_Phy/Target -I../../../Core/Inc -I../../../../../../../../Utilities/misc -I../../../../../../../../Utilities/timer -I../../../../../../../../Utilities/trace/adv_trace -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/BSP/B-L072Z-LRWAN1 -I../../../../../../../../Drivers/BSP/CMWX1ZZABZ_0xx -I../../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../../../../../Middlewares/Third_Party/SubGHz_Phy/sx1276 -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_app/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_device/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_generate/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_util/Inc" -Os -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Usercode/user_change/Src/user_uart.o: C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Src/user_uart.c Usercode/user_change/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32L072xx -DCMWX1ZZABZ0XX -DDEVICE_TYPE_STATION -c -I../../../SubGHz_Phy/App -I../../../SubGHz_Phy/Target -I../../../Core/Inc -I../../../../../../../../Utilities/misc -I../../../../../../../../Utilities/timer -I../../../../../../../../Utilities/trace/adv_trace -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/BSP/B-L072Z-LRWAN1 -I../../../../../../../../Drivers/BSP/CMWX1ZZABZ_0xx -I../../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../../../../../Middlewares/Third_Party/SubGHz_Phy/sx1276 -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_app/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_change/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_device/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_generate/Inc" -I"C:/Users/MDBK/Desktop/BSR_Software_V130/Usercode/user_util/Inc" -Os -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-Usercode-2f-user_change-2f-Src

clean-Usercode-2f-user_change-2f-Src:
	-$(RM) ./Usercode/user_change/Src/user_adc.cyclo ./Usercode/user_change/Src/user_adc.d ./Usercode/user_change/Src/user_adc.o ./Usercode/user_change/Src/user_adc.su ./Usercode/user_change/Src/user_at.cyclo ./Usercode/user_change/Src/user_at.d ./Usercode/user_change/Src/user_at.o ./Usercode/user_change/Src/user_at.su ./Usercode/user_change/Src/user_i2c.cyclo ./Usercode/user_change/Src/user_i2c.d ./Usercode/user_change/Src/user_i2c.o ./Usercode/user_change/Src/user_i2c.su ./Usercode/user_change/Src/user_internal_mem.cyclo ./Usercode/user_change/Src/user_internal_mem.d ./Usercode/user_change/Src/user_internal_mem.o ./Usercode/user_change/Src/user_internal_mem.su ./Usercode/user_change/Src/user_obis.cyclo ./Usercode/user_change/Src/user_obis.d ./Usercode/user_change/Src/user_obis.o ./Usercode/user_change/Src/user_obis.su ./Usercode/user_change/Src/user_uart.cyclo ./Usercode/user_change/Src/user_uart.d ./Usercode/user_change/Src/user_uart.o ./Usercode/user_change/Src/user_uart.su

.PHONY: clean-Usercode-2f-user_change-2f-Src

